/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as GachaRouteImport } from './routes/gacha'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StudyRouteImport } from './routes/study'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as BattleBattleIdRouteImport } from './routes/battle.$battleId'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const GachaRoute = GachaRouteImport.update({
  id: '/gacha',
  path: '/gacha',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleBattleIdRoute = BattleBattleIdRouteImport.update({
  id: '/battle/$battleId',
  path: '/battle/$battleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassesRoute,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => ClassesRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRouteWithChildren
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/gacha': typeof GachaRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/classes/': typeof ClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/gacha': typeof GachaRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/classes': typeof ClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRouteWithChildren
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/gacha': typeof GachaRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/classes/': typeof ClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classes'
    | '/collection'
    | '/dashboard'
    | '/feed'
    | '/gacha'
    | '/inventory'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/study'
    | '/tasks'
    | '/battle/$battleId'
    | '/classes/$classId'
    | '/join/$code'
    | '/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collection'
    | '/dashboard'
    | '/feed'
    | '/gacha'
    | '/inventory'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/study'
    | '/tasks'
    | '/battle/$battleId'
    | '/classes/$classId'
    | '/join/$code'
    | '/classes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/classes'
    | '/collection'
    | '/dashboard'
    | '/feed'
    | '/gacha'
    | '/inventory'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/study'
    | '/tasks'
    | '/battle/$battleId'
    | '/classes/$classId'
    | '/join/$code'
    | '/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  GachaRoute: typeof GachaRoute
  InventoryRoute: typeof InventoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  StudyRoute: typeof StudyRoute
  TasksRoute: typeof TasksRoute
  BattleBattleIdRoute: typeof BattleBattleIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gacha': {
      id: '/gacha'
      path: '/gacha'
      fullPath: '/gacha'
      preLoaderRoute: typeof GachaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$battleId': {
      id: '/battle/$battleId'
      path: '/battle/$battleId'
      fullPath: '/battle/$battleId'
      preLoaderRoute: typeof BattleBattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClassesRouteChildren {
  ClassesClassIdRoute: typeof ClassesClassIdRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesClassIdRoute: ClassesClassIdRoute,
  ClassesIndexRoute: ClassesIndexRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClassesRoute: ClassesRouteWithChildren,
  CollectionRoute: CollectionRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  GachaRoute: GachaRoute,
  InventoryRoute: InventoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  StudyRoute: StudyRoute,
  TasksRoute: TasksRoute,
  BattleBattleIdRoute: BattleBattleIdRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
